### ISSUE TITLE
提供百度云盘的apk安装包安装不了

### ISSUE THREAD

**Issue by jarvan11** [pengguanming/ElemeNestedScrolling#1]
提供百度云盘的apk安装包安装不了，报错：INSTALL_PARSE_FAILED_NO_CERTIFICATES

**Comment by pengguanming** [comment]
不好意思，我打包时只勾选了V2签名，对一些手机安装可能有影响，您可以clone这个项目的源码导入AndroidStudio编译安装到您的手机
